apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-3

  superuserSecret:
    name: dev-ksb-postgres-super-user

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: dev
      owner: ksb
#      postInitApplicationSQLRefs:
#        - name: dev-postgres-init
#          key: postgres-init.sql
      secret:
        name: dev-ksb-postgres-user

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: standard
      volumeMode: Filesystem

  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"

    pg_hba: []