apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: airflow
      owner: airflow
      secret:
        name: ksb-postgres-user

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: standard
      volumeMode: Filesystem